# Generated by Django 4.2.1 on 2023-07-21 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_fooditems_availability_fooditems_category_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='EndTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='StartTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
